<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://www.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.holon-platform.vaadin</groupId>
		<artifactId>holon-vaadin-flow-root</artifactId>
		<version>10.0.2</version>
	</parent>

	<artifactId>holon-vaadin-flow-chartjs</artifactId>

	<name>${project.groupId}:${project.artifactId}</name>
	<description>Holon Vaadin Flow Chart.js web components integration</description>

	<url>https://holon-platform.com</url>

	<dependencies>
		<dependency>
			<groupId>com.holon-platform.vaadin</groupId>
			<artifactId>holon-vaadin-flow</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifestEntries>
							<Automatic-Module-Name>com.holonplatform.vaadin.flow.chartjs</Automatic-Module-Name>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>




