package com.holonplatform.vaadin.flow.ai.datastore;

import java.util.regex.Pattern;

/**
 * Read-only SQL guard used by {@link DatastoreDatabaseProvider} to enforce that only
 * {@code SELECT} statements generated by the LLM are ever executed.
 *
 * <p>This is a defense-in-depth check: the primary guarantee must still come from backing the
 * query execution with a database account that only has read privileges (see the
 * {@code security-and-guardrails} guidance). This guard rejects obviously unsafe statements
 * (multiple statements, DDL/DML keywords, comments used to smuggle a second statement) before
 * they ever reach the connection.
 */
public final class ReadOnlySqlGuard {

    private static final Pattern FORBIDDEN_KEYWORDS = Pattern.compile(
            "(?i)\\b(INSERT|UPDATE|DELETE|MERGE|DROP|ALTER|CREATE|TRUNCATE|GRANT|REVOKE|EXEC|EXECUTE|CALL)\\b");

    private ReadOnlySqlGuard() {
    }

    /**
     * Returns {@code true} if the given SQL text is a single, read-only {@code SELECT}
     * (or {@code WITH ... SELECT}) statement with no embedded write/DDL keywords or
     * statement-separating semicolons.
     *
     * @param sql the SQL text to check (may be null)
     * @return {@code true} if the statement is considered safe to execute read-only
     */
    public static boolean isReadOnlySelect(String sql) {
        if (sql == null) {
            return false;
        }
        String trimmed = stripTrailingSemicolon(sql.strip());
        if (trimmed.isEmpty()) {
            return false;
        }
        // Reject multiple statements smuggled via an internal semicolon.
        if (trimmed.contains(";")) {
            return false;
        }
        String upperStart = trimmed.toUpperCase(java.util.Locale.ROOT);
        if (!(upperStart.startsWith("SELECT") || upperStart.startsWith("WITH"))) {
            return false;
        }
        return !FORBIDDEN_KEYWORDS.matcher(trimmed).find();
    }

    private static String stripTrailingSemicolon(String sql) {
        String result = sql;
        while (result.endsWith(";")) {
            result = result.substring(0, result.length() - 1).stripTrailing();
        }
        return result;
    }

}
