<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.holon-platform.vaadin</groupId>
		<artifactId>holon-vaadin-flow-root</artifactId>
		<version>12.0.1-SNAPSHOT</version>
	</parent>

	<artifactId>documentation-vaadin-flow</artifactId>

	<name>${project.groupId}:${project.artifactId}</name>
	<description>Holon Vaadin Flow documentation</description>

	<url>https://holon-platform.com</url>

	<properties>
		<skipTests>true</skipTests>
		<jacoco.skip>true</jacoco.skip>
	</properties>

	<build>
		<resources>
			<resource>
				<directory>${project.basedir}/src/docs/asciidoc</directory>
			</resource>
		</resources>

		<plugins>
			<!-- Asciidoc reference documentation to HTML and PDF -->
			<plugin>
				<groupId>org.asciidoctor</groupId>
				<artifactId>asciidoctor-maven-plugin</artifactId>
				<configuration combine.self="override">
					<sourceDirectory>src/docs/asciidoc/reference</sourceDirectory>
					<attributes>
						<source-highlighter>coderay</source-highlighter>
						<endpoint-url>https://holon-platform.com</endpoint-url>
						<sourcedir>${project.build.sourceDirectory}</sourcedir>
						<project-version>${project.version}</project-version>
						<examplesdir>${project.basedir}/src/main/java</examplesdir>
						<icons>font</icons>
						<idprefix />
						<idseparator>-</idseparator>
						<docinfo1>true</docinfo1>
						<docinfodir>${project.build.directory}/maven-shared-archive-resources/documentation</docinfodir>
						<last-update-label>false</last-update-label>
						<theme>flask</theme>
						<tabsize>2</tabsize>
					</attributes>
				</configuration>
			</plugin>
			<!-- Assembly docs -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<appendAssemblyId>true</appendAssemblyId>
					<finalName>${project.artifactId}-${project.version}</finalName>
					<descriptorRefs>
						<descriptorRef>reference-docs</descriptorRef>
					</descriptorRefs>
				</configuration>
				<executions>
					<execution>
						<id>assembly-docs</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>com.iyensoft.vaadin</groupId>
			<artifactId>iyen-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.holon-platform.vaadin</groupId>
			<artifactId>holon-vaadin-flow-navigator</artifactId>
		</dependency>
		<dependency>
			<groupId>com.holon-platform.vaadin</groupId>
			<artifactId>holon-vaadin-flow-spring</artifactId>
		</dependency>
		<dependency>
			<groupId>com.holon-platform.vaadin</groupId>
			<artifactId>holon-vaadin-flow-spring-boot</artifactId>
		</dependency>

		<!-- Servlet API -->
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>

</project>

